export const ITEM_CATEGORIES = [
  'Mejeri',
  'Kött',
  'Fisk & skaldjur',
  'Grönsaker',
  'Frukt',
  'Pasta & ris',
  'Bakning',
  'Frukost',
  'Konserver',
  'Snacks',
  'Dryck',
  'Skafferi',
  'Såser & kryddor',
  'Örter & kryddor',
]
